### PR TITLE
feat: Add BOM indicator to encoding component

### PR DESCRIPTION
**Pull request by sergiuser1**
Inspired by vim-airline, it adds `[BOM]` to the encoding if the file uses byte-order mark

### CODE REVIEW

**Comment by shadmansaleh** [comment]
Does vim/neovim's builtin statusline show this by default? if not can you put it behind an option, set default to false?

**Comment by sergiuser1** [comment]
By default it doesn't have anything about file encoding, I found this about making a custom component: https://stackoverflow.com/a/10416234/11710862

I'll add the option and some tests and will update the PR.

**Comment by sergiuser1** [comment]
@shadmansaleh ping

**Comment by sergiuser1** [comment]
Thanks!

**Pull request merged**
