### PR TITLE
feat: refresh lualine based on timer + winbar support. (experimental)

### LINKED ISSUE #744: Feat: global statusline should still displays for all filetypes, including `ignored_filetypes`
### Requested feature
When global statusline is used, statusline should works for all buffer, including those in `disabled_filetypes` tables.

### Motivation

`disabled_filetypes` is used to prevent rendering a crammed statusline in overly small windows, this doesn't apply with global statusline.

- One option is just to not disabled any filetypes, but that means winbar (if it is ever officially supported #736 ) will not ignore some filetypes with small windows either.
- Another option is to have separate options, i.e `statusline_disabled_filetypes` and `winbar_disabled_filetypes` (again if it's ever supported)
- Or just ignore `ignored_filetypes` altogether when using global statusline.

### PR DESCRIPTION
**Pull request by shadmansaleh**
### Needs testing

Try testing this branch and if you find any issue let me know in comment

### What it is
With this lualine will control it's own refresh instead of relying on nvim.

If we refresh this way we should be able to change out the statusline, winbar, tabline options and still be running . We should be able to address https://github.com/nvim-lualine/lualine.nvim/pull/689#issuecomment-1157194479 & #395 with this style of update.

### Major changes
-  lualine now refresh based on timer + some auto-commands.
- added `require('lualine').refresh` function to force refresh lualine . It can refresh all statusline, tabline, winbars or can granularly refresh specific statusline/tabline/winbar of specific windows see the code docs for more info.
-  winbar support. (originally form #689 by @diegodox)
- winbar support in extensions.
-  newly added options
    - options.refresh.statusline
    - options.refresh.tabline
    - options.refresh.winbar 
    -  options.disabled_filetypes.statusline
    -  options.disabled_filetypes.winbar
    -  winbar
    -  inactive_winbar
-  various bug fixes.

### known Issues/todos:
- ~~Refresh time is set to 1s . It seems when changing wins inactive & active stls don't switch immediately instead takes that 1s to update which is quite noticeable . Possible solutions: utilize autocommads to refresh on such events.~~
- ~~We need to handle errors in the refresh funcitnon so if we say fail to update 3 times in a row we should stop the timer~~.
- ~~looks like nvim wants to put winbars on floating windows too. but it might fail if there aren't enough room like telescopes prompt . that's an issue for us. wonder if we can determine if a win is float or not and skip floats 🤦‍♂️~~ (skiping winbar on winheight <= 1 & floating windows)
- ~~try merging statusline_dispatch and winbar_dispatch togather they have a lot of duplication~~
- ~~statusline doesn't seem to update regularly in cmdline mode~~
- ~~nvim-0,5 & 0.6 is broken with nvim_opts module . (may we should just have compat tags for older nvim version and be done with them . keeping support for them is getting annoying )~~
- ~~live update seems broken for gobalstatus & separators options.~~
- yes we have that intro disappearing due to redraw issue again.

closes #744 #692
supersedes #689

### CODE REVIEW

**Comment by shadmansaleh** [comment]
I don't think that's the case here. We are respecting disabled filetypes but It seems telescope is creating 6 windows but it only marks 2 of those with filetype TelescopeResults and TelescopePrompt. I'm not using floaterm but toggleterm seems to work correctly with disabled_filetype. Maybe floaterm does something similar to telescope.

**Comment by lkhphuc** [comment]
> Also it seems floating windows don't use global value of winbar option so in previous pr floating windows didn't have winbar at all even without you adding the filetypes to disabled list

I wonder if this is desired behaviour in most case.

**Comment by shadmansaleh** [comment]
> I wonder if this is desired behaviour in most case.

**Comment by lkhphuc** [comment]
Another thing I notice is that this with this branch, my `showtabline` is set to 1, even though I have `vim.o.showtabline=0` in my config.

**Comment by lkhphuc** [comment]
It fixes the issue. All seems good to me now.

**Comment by shadmansaleh** [comment]
What kind of window layout do you have when this happens . Since you're saying it happens on key press do is it possible some small completion popups or similar are appearing ? Though we should already be ignoring popups.

**Comment by lkhphuc** [comment]
I have figured out one reproducible case for the error above, it's due to the small popup window when using https://github.com/stevearc/dressing.nvim 
Everytime I trigger a rename function, I got the "not enough room" above.

**Comment by shadmansaleh** [comment]
I'm not sure but it seems the original window is actually the one throwing error not the floating window . Which is odd because it does have enough space to draw the winbar . Do you think you can reproduce this without any other plugin ?

**Comment by lkhphuc** [comment]
I use https://github.com/andymass/vim-matchup with this config to get a popup window display on the right like this for very long function: 
```
  use {"andymass/vim-matchup",
    config = function ()
      vim.g.matchup_matchparen_offscreen = {method= 'popup', position='cursor'}
    end
  }
```
Screenshot 2022-07-20 at 18 49 46

Now if I press anything, enter insert, command mode etc I will get this "not enough room" error. I will have to move the cursor elsewhere first.

**Comment by shadmansaleh** [comment]
@lkhphuc I think a bug in neovim is causing the issue you're facing . I've opened an issue in neovim's repo https://github.com/neovim/neovim/issues/19464 lets what the devs think about it.

**Comment by shadmansaleh** [comment]
I think this branch is quite stable . I can probably merge it already . I anyone want can take it for a spin and see if there are any inconsistencies.

**Comment by willnorris** [comment]
This seems to be causing a problem with `set wildmode=list`... the command line completion list displays for just  a second, and then disappears.  Reverting to 8d956c1 fixes the behavior, so it definitely seems to be caused by this.

**Comment by shadmansaleh** [comment]
@willnorris  fixed in 6fbc35b

**Pull request merged**
