### PR TITLE
Create simple.lua

### PR DESCRIPTION
**Pull request by bryant-the-coder**
I created this as a theme. I was asking a tons of simple yet annoying question to do this theme. I hope my PR is accepted.

### CODE REVIEW

**Comment by shadmansaleh** [comment]
Example configs are there to show new ideas about lualine config. So users can easily incorporate those ideas in there config or take inspiration from them.

For example:
- evilline: Showed ways to break traditional lualine configs and get completely new look compared to default.
- bubbleline: Showcased using section separators on component when they were added.
- slanted-gap: Showed using custom components. And how lualine can be used easily to create unique looks.

What does this add ?

**Comment by bryant-the-coder** [comment]
Some simple aesthetic looks maybe? Tried my best. It is ok if it doesn't fits. It suits me :)

**Comment by shadmansaleh** [comment]
> Some simple aesthetic looks maybe? 

Sorry but asthetics isn't the point of examples they are there to show new ideas about configuring.

> Tried my best

Yes. Thanks for your effort and considering to contribute to lualine.

> It suits me :)

Glad to here that :)

**Comment by bryant-the-coder** [comment]
Noted sir

**Pull request closed without merging**
