### PR TITLE
docs: Add lazy.nvim installation instructions. (#1140)

### PR DESCRIPTION
**Pull request by Chris1320**

### CODE REVIEW

**Comment by Chris1320** [comment]
I based this from my [lualine.nvim configuration](https://github.com/SetupGuides/Neovim/blob/main/src/lua/plugins/lualine.lua). I am not sure if `lazy = false` is required.

**Comment by Chris1320** [comment]
I looked up other people's configs, and it seems like `event = "VeryLazy"` is the most common configuration.

**Comment by MikeTheGreat** [comment]
I'm a neovim and lualine newbie, but I tried this and it worked.  

I figured I'd throw that confirmation out there in the hopes that it helps to speed the adoption/merge of this commit :)

**Comment by CatherineF-dev** [comment]
I tried and it worked. lazy = false is not required.

**Comment by shadmansaleh** [comment]
lgtm. thanks for your contribution.

**Pull request merged**
