### PR TITLE
Add option to show buffer number + alternate file icon

### PR DESCRIPTION
**Pull request by MrcJkb**
This is a rough draft to address #668.
Still needs documentation (and maybe a test spec), which I will add if the feature request is approved.

### CODE REVIEW

**Comment by shadmansaleh** [comment]
I like the idea of identifying alternate buffer .

I think we should just make mode 4 & 5 that are same as 2 & 3 but shows bufnr instead if buffer index .

**Comment by shadmansaleh** [comment]
I like the idea of identifying alternate buffer .

I think we should just make mode 4 & 5 that are same as 2 & 3 but shows bufnr instead if buffer index .

**Comment by MrcJkb** [comment]
> I like the idea of identifying alternate buffer .
> 
> I think we should just make mode 4 & 5 that are same as 2 & 3 but shows bufnr instead if buffer index .

Sure. What about the default behaviour?
Would you like to preserve the current default `mode = 2`?
I would suggest changing the default `mode` to 0, as that is what is set in the readme example. But it may surprise users who don't have `mode` set in their configs after an update...

Regarding the alternate buffer identifier: Would you prefer an option to enable/disable it?

**Comment by shadmansaleh** [comment]
> What about the default behaviour?
Would you like to preserve the current default mode = 2?

Current default mode is 0 no reason to change that. It's set [here](https://github.com/nvim-lualine/lualine.nvim/blob/45d07fc026400c211337a7ce1cb90e7b7a397e31/lua/lualine/components/buffers/init.lua#L12) by the way . I think you thought it's 2 because of that functions  structure.

> Regarding the alternate buffer identifier: Would you prefer an option to enable/disable it?

You can expose it as an option under symbols table .
```lua
options.symbols = {
  modified = ....,
  alternate_file = ....,
}
```
Similar to how diff & diagnostics component exposes their icons . That way if someone doesn't want it they can just set it to empty string.

**Comment by shadmansaleh** [comment]
You need to have plenary.nvim . Then run `make test` . See [here](https://github.com/nvim-lualine/lualine.nvim/blob/master/CONTRIBUTING.md#devloper-tools)

**Comment by MrcJkb** [comment]
I am getting inconsistent buffer numbers in my tests between NeoVim 0.5 and 0.6.
Are some tests excluded depending on the NeoVim version? It won't be possible to reset buffer indexing without quitting the session.

**Comment by shadmansaleh** [comment]
> I am getting inconsistent buffer numbers in my tests between NeoVim 0.5 and 0.6.

This is something I've noticed too . You can try matching a pattern instead of exact number . Or you could get the bufnr for the bufname and test against that . That way you'll be varifying the bufnr too in the test though pattern match is easier to write as it's built into statusline test module :)

> Are some tests excluded depending on the NeoVim version?

Not currently . Though you could run different test code in the test based on which nvim version you're on , probably not a good idea in this case as it might break the test on nightly or a new version anytime.

**Comment by MrcJkb** [comment]
I implemented the bufnr detection. It turns out that the inconsistency is because NeoVim 0.5 does not create an unnamed buffer. By silently deleting the alternate buffer after creating the first buffer `a.txt`, we can achieve consistent results.

**Review by shadmansaleh — APPROVED** [review]

**Comment by shadmansaleh** [comment]
lgtm , thanks.

**Pull request merged**
