### PR TITLE
Fix estimated with calculation

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Re-pr due to bugs introduced in manual merge of 
https://github.com/nvim-lualine/lualine.nvim/pull/265

### CODE REVIEW

**Comment by shadmansaleh** [comment]
Seems good to me . Can you resolve the conflicts?

**Comment by NullVoxPopuli** [comment]
ohh, lemme try updating to that / this / the one true branch and see if my issue is solved :sweat_smile:

**Comment by NullVoxPopuli** [comment]
home, something is still broken, I'll take a look at the current code and re-apply my changes

**Comment by NullVoxPopuli** [comment]
For example (using `nvim-lualine` now), this has a ton of space, yet the path is shortened
image

**Comment by NullVoxPopuli** [comment]
though at first glance, the logic looks right :thinking: gonna need to do some digging here hmm

**Comment by gonzaloserrano** [comment]
currently testing
```
require('lualine').setup{
  sections = {
	lualine_c = { {'filename', file_status = false, full_path = true, shorten = false } },
  },
}
```
and got shorten name with no path in a pretty big screen 🤔 
CleanShot 2023-02-21 at 18 18 07@2x

**Pull request closed without merging**
