### PR TITLE
fix: Replace battle.net icon with sharing screen

### PR DESCRIPTION
**Pull request by Anakael**
I replaced battle.net icon with xf838 as it described in comment.
But I think it is still not appropriate icon and I'd appreciate suggestion about it.

### CODE REVIEW

**Comment by shadmansaleh** [comment]
IIRC symbol for hint is a `lightbulb` . It might have been miss labeled if xf838 is not that 🤦‍♂️ . Not sure where battle.net icon came from what font are you using ?

**Comment by Anakael** [comment]
I am using Noto Sans with with `Nerd` patch.
Battle.net icon is xf835 and probably was copied by accident.

**Comment by shadmansaleh** [comment]
> Battle.net icon is xf835

xf835 is lightbulb in nerdfonts according to https://www.nerdfonts.com/cheat-sheet

I think there's something wrong with the patch on font you're using . I'm using fira-code and it gets displayed as lightbulb.

You can fix the documentation error in this pr but I don't think we should change the hint icon to sharing screen

**Comment by Anakael** [comment]
I've fixed commentary :)

**Review by shadmansaleh — APPROVED** [review]

**Comment by shadmansaleh** [comment]
lgtm . Thanks :)

**Pull request merged**
