### PR TITLE
try to highlight nvim-web-devicon

### LINKED ISSUE #822: Feat: highlight nvim-web-devicon color in buffers component
### Requested feature

`nvim-web-devicons` returns a highlight group with the icon. Highlight the icon with it.

### Motivation

Because it looks better with colored icons.

### PR DESCRIPTION
**Pull request by mrjones2014**
Fixes #822 

This PR need some help. I did a first pass, but need to set the bg color for the icon on inactive buffers.

### CODE REVIEW

**Comment by mrjones2014** [comment]
Not sure how to fix the rest but there's a start here.

**Comment by shadmansaleh** [comment]
Check out how filetype component does it.

**Comment by mrjones2014** [comment]
I tried but I can't quite figure it out, any advice?

**Comment by mrjones2014** [comment]
Lualine was crashing my entire Neovim so I've switched off it.

**Pull request closed without merging**
