### PR TITLE
fix: remove url-encoding chars in filename

### PR DESCRIPTION
**Pull request by liuerfire**
fixes https://github.com/nvim-lualine/lualine.nvim/issues/820

### CODE REVIEW

**Comment by shadmansaleh** [comment]
That's strange % in there should be escaped by `utils.stl_escape()` in following line it it shouldn't throw error.

**Comment by liuerfire** [comment]
I'm not sure this should be fixed by lualine or by jdtls :cry: But this commit did fix #820.

Feel free to close this MR 'cause I don't think this is a good solution either 😄

**Comment by 1Jo1** [comment]
at least this annoying bug is fixed :)

why not just like escaping `%`
```
function M.stl_escape(str)
  if type(str) ~= 'string' then
    return str
  end
  return str:gsub('%%', '%%%%'):gsub('%%', '')
end
```

**Comment by 1Jo1** [comment]
> That's strange % in there should be escaped by `utils.stl_escape()` in following line it it shouldn't throw error.

 `str:gsub('%%', '%%%%'):` it doesn't escaped '%', it actually % will be added

**Comment by shadmansaleh** [comment]
> str:gsub('%%', '%%%%') it doesn't escaped %, it actually % will be added

In statusline %% is displayed as % just like how in most regular strings \\ is displayed as \

**Comment by 1Jo1** [comment]
> > str:gsub('%%', '%%%%') it doesn't escaped %, it actually % will be added
> 
> In statusline %% is displayed as % just like how in most regular strings \ is displayed as \

sorry I'm really confused, I just tried lua in terminal:
```
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
> 
> string.gsub('%%', '%%', '%%%%')
%%%%  2
> 
```
according to you, result should be `%` right? 
maybe I'm just not familiar with Lua/Neovim or I miss something else?

**Comment by 1Jo1** [comment]
what do you think? @shadmansaleh

**Pull request closed without merging**
