### PR TITLE
feat: add workspace diagnostics source

### PR DESCRIPTION
**Pull request by ybbond**
this method is from my own config to add workspace diagnostic to the component table.

### CODE REVIEW

**Comment by shadmansaleh** [comment]
What do you mean by workspace diagnostics and how is it different from current nvim_diagnostic source?

**Comment by fitrh** [comment]
@shadmansaleh `nvim_diagnostic` returns the diagnostics for current buffer (document diagnostics), passing `nil` as `bufnr` for `vim.diagnostic.get` will return diagnostics of all buffers (workspace diagnostics)

**Comment by shadmansaleh** [comment]
I'm not sure if nvim lsp has a notation of workspaces yet. If all buffers mean all open buffers from different projects that would kind of annoying right ?

**Comment by AnonymusRaccoon** [comment]
Passing nil to the bufnr does return the diagnostic for every file in the workspace, not opened ones only. This is also what is used in [trouble.nvim](https://github.com/folke/trouble.nvim/blob/main/lua/trouble/providers/diagnostic.lua#L10).

**Comment by AnonymusRaccoon** [comment]
@shadmansaleh Is there a reason this hasn't been merged yet?

**Comment by changyiyao** [comment]
> I'm not sure if nvim lsp has a notation of workspaces yet. Also even if nvim lsp had workspaces unlikely diagnostics module does. If all buffers mean all open buffers from different projects that wouldn't be very useful right ?

See this PR: https://github.com/nvim-lualine/lualine.nvim/pull/759.
nvim.diagnostic.get() without bufnr param will get workspace dianogstics from LSP server no matter whether the buffer is opened.

**Comment by shadmansaleh** [comment]
Sorry I kind of forgot about this pr .I think we can merge it.

**Pull request merged**
